version: '3'
services:
  ms_users1:
    image: alfredobarron/microservice-users:1
    ports:
     - "5001:5000"
  ms_users2:
    image: alfredobarron/microservice-users:1
    ports:
     - "5002:5000"
  ms_users3:
    image: alfredobarron/microservice-users:1
    ports:
     - "5003:5000"
  ms_posts1:
    image: alfredobarron/microservice-posts:1
    ports:
     - "5004:5000"
  ms_posts2:
    image: alfredobarron/microservice-posts:1
    ports:
     - "5005:5000"
  ms_comments1:
    image: alfredobarron/microservice-comments:1
    ports:
     - "5006:5000"
  ms_comments2:
    image: alfredobarron/microservice-comments:1
    ports:
     - "5007:5000"
  api_gateway:
    image: alfredobarron/loadbalancig-microservices:1
    ports:
     - "8080:80"        